services:
  - type: web
    name: parkinson-app
    runtime: python
    runtimeVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: a52946ffee9d597cf2ef4afd3ec59e1465f83db61b9c7f4dc7686a4f627daa8b
      - key: DATABASE_URL
        sync: false